### ISSUE TITLE
Prototypes/Classes. TODO

### ISSUE THREAD

**Issue by NovikovEvgeny** [NovikovEvgeny/js-talks#40]
# Изменения
- [x] Пофиксить подгрузку кодсниппетов
- [x] Добавить информацию про own properties, `Object.defineProperty` (esp. enumerable), `for` loop, `for .. in` , `for ... of`, `Object.keys/values/entries` и остальные варианты циклов
- [x] Добавить #private variables and methods
- [x] Добавить getters and setters
- [ ] Добавить ссылки на дополнительные источники и "почитать ещё"
